database_servers:
  hosts:
    database_server01:
      ansible_host: 172.19.0.4
    database_server02:
      ansible_host: 172.19.0.2
    database_server03:
      ansible_host: 172.19.0.3

    
web_servers:
  hosts:
    webserver01:
      ansible_host: 192.0.2.140
    webserver02:
      ansible_host: 192.0.2.150
    webserver03:
      ansible_host: 192.0.2.150
      
      
# always adhere to indentation rules, ansible pretty much depends on it
